# Generated by Django 2.1.2 on 2018-12-30 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181230_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='blog.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='user_actions',
            name='fav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_post', to='blog.Post'),
        ),
    ]
